feat: Expose `Trie` methods for `JellyfishMerkleTrie`
vrrb-io/patriecia pull request #17
Opened 2023-07-21 22:01 UTC by eureka-cpu

Adds implementations for `Database` on `MockTreeStore` and `Trie` on `JellyfishMerkleTree`, exposing methods that are already in use by the protocol codebase.

Closes #16 

This will likely introduce some small breaking changes. Here are the changes I foresee:

- The test database provided by the `jmt` library, `MockTreeStore`, is looking like a much better fit for testing than `MemoryDB` since it was built for the same reasons but is already fully integrated into `jmt`. In my opinion it makes sense to just deprecate `MemoryDB` in favor of it.
- The `get` method for the `Trie` trait takes only a `pmt::Key`(`&[u8]` under the hood), however this is insufficient for `jmt` which has an optimized `get` method that needs a `KeyHash`(` [u8; 32]`) & `Version`(`u64`). This may end up being a trivial change if we can update `Trie` to accommodate `jmt`'s needs and then call the underlying function that the original `get` method calls (`get_without_proof`).
- In general some changes may need to be made to the `Trie` trait as mentioned above that may introduce small breaking changes. This may be unavoidable since the original tree it was implemented for is inherently different than `jmt`, but I don't anticipate the changes to be major, nor unreasonable.

2023-07-26 16:57 UTC, nopestack commented on jmt/src/db.rs
> +use pmt::Key;
minor: preferably abstract this to a third crate, called common or types or something along these lines, remember that we intend to remove pmt altogether in the future.

2023-07-26 17:03 UTC, eureka-cpu commented on jmt/src/db.rs
> +use pmt::Key;
I'm currently only using it for the time being while transitioning the trait methods

2023-07-26 17:18 UTC, nopestack commented on jmt/src/db.rs
> +    // length of what? nodes? values?
This should represent the count of all the values stored within the underlying db

2023-07-26 17:19 UTC, nopestack commented on jmt/src/db.rs
> +    fn value_history(&self) -> HashMap<KeyHash, Vec<(Version, Option<OwnedValue>)>>;
why KeyHash instead of NodeKey?

2023-07-26 17:26 UTC, nopestack commented on jmt/src/trie.rs
> +    fn commit(&mut self) -> Result<H>;
style: consider renaming to flush so this is consistent with the homologous operation on VersionedDatabase

2023-07-26 17:27 UTC, nopestack commented on jmt/src/tree.rs
>      reader: &'a R,
why do we need a reference to this reader?

2023-07-26 17:30 UTC, nopestack commented on jmt/src/mock.rs
> +    pub fn put_key_preimage<H: SimpleHasher>(&self, preimage: &Vec<u8>) {
What's a preimage? can this type be named instead of it being a byte vector?

2023-07-26 17:32 UTC, nopestack commented on jmt/src/tree.rs
> +    fn get(&self, key: KeyHash, version: Version) -> Result<Option<OwnedValue>> {
style: Consider flattening the result type if possible, i.e. minimize Result-wrapped Options as much as possible.

2023-07-26 17:34 UTC, nopestack commented on jmt/src/tree.rs
> +    fn commit(&mut self) -> Result<H> {
minor: this one is meant to be called frequently, can it be implemented proper?

2023-07-26 18:43 UTC, eureka-cpu commented on jmt/src/db.rs
> +    // length of what? nodes? values?
the underlying db for jmt is more complex than the previous db, which leaves the question: what exactly was the previous hashmap storing? the key hash and value hash, the node key and the node?

2023-07-26 18:43 UTC, eureka-cpu commented on jmt/src/db.rs
> +    fn value_history(&self) -> HashMap<KeyHash, Vec<(Version, Option<OwnedValue>)>>;
for the value history that was the type needed

2023-07-26 18:50 UTC, eureka-cpu commented on jmt/src/trie.rs
> +    fn commit(&mut self) -> Result<H>;
Will look into the naming semantics here and try to come to a conclusion on which one makes more sense

2023-07-26 18:50 UTC, eureka-cpu commented on jmt/src/tree.rs
>      reader: &'a R,
The `TreeReader` trait is fairly engrained in the library, I figure it's reasonable to go ahead and use the methods under the hood.

2023-07-26 18:51 UTC, eureka-cpu commented on jmt/src/tree.rs
> +    fn get(&self, key: KeyHash, version: Version) -> Result<Option<OwnedValue>> {
Awesome thanks, that will make this much easier going forward

2023-07-31 20:13 UTC, eureka-cpu commented on jmt/src/mock.rs
> +    pub fn put_key_preimage<H: SimpleHasher>(&self, preimage: &Vec<u8>) {
Update: Preimage is the state of the original tree pre-hash

2023-07-31 20:15 UTC, eureka-cpu commented on jmt/src/trie.rs
> +    fn commit(&mut self) -> Result<H>;
Looks like the JMT library actually handles caching innately with it's own insertion method, which is convenient for working with a database. This way the database just needs to worry about storing the end values and not keeping track of caches that have yet to be committed.

2023-07-31 20:21 UTC, eureka-cpu commented on jmt/src/tree.rs
> +    fn commit(&mut self) -> Result<H> {
See comment above regarding `jmt` caching and interaction between the tree state and storage

2023-07-31 20:23 UTC, eureka-cpu commented on jmt/src/db.rs
> +    fn value_history(&self) -> HashMap<KeyHash, Vec<(Version, Option<OwnedValue>)>>;
to elaborate, the field `value_history` has type `HashMap<KeyHash, Vec<(Version, Option<OwnedValue>)>>`

2023-07-31 21:53 UTC, nopestack commented on jmt/src/mock.rs
> +            .expect("failed to get value"))
blocking: forward this error instead of panicking

2023-07-31 21:57 UTC, nopestack requested changes
Please address the two blocking issues pointed out

2023-07-31 22:01 UTC, nopestack approved these changes

2023-07-31 22:37 UTC, merged